[package]
name = "meme-emoji-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inventory = "0.3"
serde = "1.0"
tween = { version = "2.2" }
skia-safe = { version = "0.93", features = ["textlayout"] }

meme_generator_core = "0.0.5"
meme_generator_utils = "0.0.9"
rand = "0.10"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
